### ISSUE TITLE
darth vader / rey / capt marvel watches need some UI work

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#100]
These are touch screen but seem to be different than the venu or vivoactive in the way you interact with it. Also they share the same screen size as devices with buttons but don't really have any so the layouts need to be tweaked a little.
![image](https://user-images.githubusercontent.com/814623/88345326-5b668080-cd0b-11ea-94bd-6c389b12a990.png)

**Comment by arquicanedo** [comment]
I'll adjust the superhero watch UIs.

**Comment by arquicanedo** [comment]
Top-right button - Settings
Bottom-right button - Back
Click on screen - toggle / enter Steak Menu
Scroll down - Smoking menu
Scroll up - Settings menu / Smoke menu

DurationPicker - **This is working OK**
Click on arrows - increase/decrease
Top-right button - go to the next time selection / finalize selection
Top-bottom button - go to previous time selection

I'll fix this tomorrow.

**Comment by arquicanedo** [comment]
Vivoactive4S uses the same type of interface. Fixed.

**Comment by arquicanedo** [comment]
Vivoactive4 as well. Fixed.

**Comment by arquicanedo** [comment]
First Avenger as well. Fixed.

**Comment by arquicanedo** [comment]
Venu as well. Fixed

**Comment by arquicanedo** [comment]
I'm sure more of these type of watches will come out as we test the rest. Will keep this one open.

**Comment by arquicanedo** [comment]
Closing this. All the watches with weird button layouts are fixed individually.
