### ISSUE TITLE
[Memory] D2 Bravo runs out of memory on switch to SteakMenu

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#101]
I will check the icons sizes later.

**Comment by arquicanedo** [comment]
Several of the 218x218 watches with physical buttons crash due to memory.

**Comment by nilsbenson** [comment]
did some tweaking of things for these low-mem devices but there's still issues. We will probably need to segregate the small/medium icon image resources from the large/extra large resources based on device and update the jungle file as appropriate. I think we're just using too much memory for the static resources

**Comment by arquicanedo** [comment]
After I'm done with all the GUI adjustments I'll start downsizing the icons on the low-mem devices.

**Comment by arquicanedo** [comment]
Other affected watches:
- D2 Bravo Titanium
-

**Comment by arquicanedo** [comment]
The memory profiler shows this split of memory usage when loading the main screen on the D2 Bravo. The Code section takes +30Kb. I'll start refactoring to see if we can reduce that footprint.

The Global section are the variables we persist, and all the Rez hierarchy. This is very small.

![image](https://user-images.githubusercontent.com/44371316/90056039-3fbc1d80-dcac-11ea-91db-817eafb1e799.png)

**Comment by arquicanedo** [comment]
A workaround to this is to change the maxSteaks down to 2 in the D2 Bravo. Perhaps this is the cleanest solution at the moment.

**Comment by arquicanedo** [comment]
- D2 Bravo, D2 Bravo Titanium solved by excluding smoke. 
- Fenix 3, Fenix 3 HR still have a problem. Even by reducing the maxSteaks to 1. --> Perhaps eliminate suppor for these two.
