### ISSUE TITLE
App cleanup, SoC for controllers/UI, etc.

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#18]
There's not an easy way to contact a developer on github so I'm opening this issue. 

I have forked this project and made a large number of changes to it to both increase the functionality, and refactor things to make it easier to maintain/add features moving forward.

- adds vibration and sound when flip timer ends
- uses Menu2 for selecting times
- adds a custom picker for the timer duration
- changes activity recording to prompt when the application ends rather than between runs of the flip (to make it easier to manage multi-step cooking processes in the future)
- general UI spacing adjustments

the branch I'm working in can be found here:

https://github.com/nilsbenson/barbecueboss/tree/cleanup-ui

let me know if you're interested in moving forward with this and I can submit a pull request or whatever. we can work out how you want to handle it. I'm not trying to step on anyone's toes, I just found the app interesting and thought I had a lot I can contribute.

**Comment by arquicanedo** [comment]
@nilsbenson thanks for reaching out! These improvements are cool. I'm definitely interested in a pull request. I'll try and test your version on my watch (Foreruner 235). If you're comfortable with it, I can reference your github account and/or your Garmin account on the release notes to give you the full credit.

**Comment by nilsbenson** [comment]
@arquicanedo sounds good. I'll run a couple tests on the simulator for the forerunner and make sure it's as good as the simulator can provide and then submit a PR.

I'm on the garmin forum as nilsbenson. send me a DM over there and I'll shoot you my e-mail address.

**Comment by arquicanedo** [comment]
@nilsbenson I ran your branch on the simulator. Going back to your points above:

- vibration and sound - I like it!
- Menu2 - I need to check the documentation but I think old watches (like mine) do not support this feature as it is part of the SDK 3. I'm getting this error when compiling for the foreruner 235. I am wondering if we can have a Menu2 for modern watches, and my old menu for old watches. This would be the workaround. I'll investigate. 
- Custom picker. I love it. 
- activity save when exiting the app. Yes, makes sense for multiple timers.
- UI spacing. Great.

Another thing I noticed is that the Flip count is reset to 0 when going back to the time selection. Thinking on how I would use this is as follows. Sometimes I think I need 2 minutes per flip, and I am already in flip 2. However, the grill gets hotter and adjusting the time to 1 minute per flip is easy with your new workflow. I simply click "back", pick 1 minute, and return to the counter. I would expect the flip count to be 3 for 1 minute. However, the current version goes back to 0.

Related to the custom picker. This makes it easy for a "smoking" mode. Perhaps future releases should extend this to hours as these sessions can last 8+ hours. Also, I need to check how a custom picker can be used in the forerunner 235 and older watches. Another thing would be to keep the timers running in the background even when the app is closed.

**Comment by nilsbenson** [comment]
Agreed on all points. I ran it on the 235 sim and I've committed and pushed a reversion back to the original menu. It still allows for the custom time period selection, but doesn't require anything outside of the 1.4 SDK. There's still some alignment and spacing issues (I fixed them on the 235, but it behaves differently on the fenix 6 and I'm still working out how to deal with it).

I've been developing professionally for 20+ years but this is my first work on anything Garmin. Bear with me a little bit as I learn the SDK and tools and we'll have a full blown project rolling in no time.

I will submit the PR today or tomorrow once I get the fenix alignment worked out and it should be good to go on "most" round devices.

**Comment by nilsbenson** [comment]
Pull request submitted. I fixed support for older SDK devices by just switching back to the original menu for now. I need to figure out how to conditionally compile things based on device/SDK family before any new SDK features can be supported on newer devices.

**Comment by arquicanedo** [comment]
@nilsabenson I tested the app over the weekend and I love the new flow. I started a branch 'multitimer' (https://github.com/arquicanedo/barbecueboss/tree/multitimer) to play around with the main menu for "Steak Selection." I haven't connected it to the new time selection menu that you created, but should be straightforward.
