### ISSUE TITLE
Select "accept" by default in promptSaveSession 

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#21]
When prompted, the current version has "cancel" as the default option. I think it makes more sense to have "accept" by default.

**Comment by nilsbenson** [comment]
I think the only way to do this is to write a custom confirmation view. Confirmation itself has no way to set the selected option or the text in those options.

**Comment by arquicanedo** [comment]
Ok. In that case I think it is better to use standard interfaces as much as possible.
