### ISSUE TITLE
Fenix 6 Layout

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#22]
Now I have a stable version using the SteakMenuLayout.xml under the multitimer branch. For some reason, the FONT_SMALL for the Fenix6 is huge in the simulator. 

The goal is to create a Fenix 6 layout that looks more reasonable that what it is now.

Below the screenshot on the f235.

![Screen Shot 2020-06-02 at 10 28 14 PM](https://user-images.githubusercontent.com/44371316/83588898-60376100-a520-11ea-9a72-e4b80af8ac0f.png)

**Comment by arquicanedo** [comment]
This is how it looks in the Fenix6 simulator. 
![Screen Shot 2020-06-02 at 10 29 54 PM](https://user-images.githubusercontent.com/44371316/83589006-ac82a100-a520-11ea-84bc-121116699f6f.png)

**Comment by nilsbenson** [comment]
I will take a look at this this week.

**Comment by nilsbenson** [comment]
I have pushed my changes to support all non-touch round devices with screen size family resources (240x240, etc.). This should keep the number of layouts to maintain low. The following is now the list of supported devices:

![image](https://user-images.githubusercontent.com/814623/83649030-5d6a5980-a57c-11ea-908d-b1beba6c5c16.png)

**Comment by nilsbenson** [comment]
and the layout on a fenix 6
![image](https://user-images.githubusercontent.com/814623/83649166-84289000-a57c-11ea-86fe-601be6d3c0d9.png)

**Comment by arquicanedo** [comment]
@nilsbenson wow that's super cool, thank you! Let's test and we can push the update over the weekend. I think this is a major release and I can't wait to use it in the field. I'll try to install it today on my watch.
