### ISSUE TITLE
Add support for rectangular devices

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#23]
There's no technical reason why we can't, and by using the screen size layouts it's pretty easy to do. I have already mocked up experimental support for the Edge 1030 and 520 and it's really just tweaking layout positions to get it to look right and adding swipe support in addition to the hard button support.

**Comment by nilsbenson** [comment]
Also needs to do a check for has :vibration so that we don't crash on devices without it.

**Comment by arquicanedo** [comment]
Added rectangle-205x148 that includes vivoactive, fr920xt, epix

**Comment by arquicanedo** [comment]
Ran all configurations of round and rectangle on the simulator (randomly picked 1 or 2 per category) and adjusted the layouts whenever required.
