### ISSUE TITLE
DurationPicker fonts out of proportion for the Venu watch

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#27]
I found this for the Venu (the only round-390). The custom PickerLayout.xml does not seem to take any effect.

I looked at the code for DurationPicker.mc. It seems that the text is hard coded and set to FONT_MEDIUM or not specified (which probably defaults in the FONT_MEDIUM). 

The option may be to exclude Venu from the list of devices.

        var title = new WatchUi.Text({:text=>Rez.Strings.durationPickerTitle, :locX=>WatchUi.LAYOUT_HALIGN_CENTER, :locY=>WatchUi.LAYOUT_VALIGN_BOTTOM, :color=>Graphics.COLOR_WHITE});

        factories[1] = new WatchUi.Text({:text=>Rez.Strings.timeSeparator, :font=>Graphics.FONT_MEDIUM, :locX =>WatchUi.LAYOUT_HALIGN_CENTER, :locY=>WatchUi.LAYOUT_VALIGN_CENTER, :color=>Graphics.COLOR_WHITE});

**Comment by nilsbenson** [comment]
I'll take a look. I saw that there's a way to pass parameters via the layout so we could probably do it that way.

**Comment by nilsbenson** [comment]
Added the ability to add a jsonData resource that specifies the font size to use for the DurationPicker. For the venu device it changes to FONT_SMALL and looks better. There is still some weirdness with the orientation of the arrows but they are ok. They look ok and work, but are rotated 90 degrees for some reason (left/right instead of up/down).

**Comment by arquicanedo** [comment]
Yes that rotation is weird. But we can ignore. Perhaps the simulator is introducing that weirdness. I think this is a closed ticket. I have the feeling that the Venu is not a very popular watch.

**Comment by nilsbenson** [comment]
#wontfix #nocomplaints

We should get this out the door and see if there's any feedback because I agree and don't think it matters much.
