### ISSUE TITLE
Long Press

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#32]
Is a long press available in the event handlers?

**Comment by nilsbenson** [comment]
I don't think a long press is available, but we may be able to fake it if we get both key up and key down events and time the down/up pairs to fire our own fake "long press".

**Comment by arquicanedo** [comment]
This would have been a good option for stopping a timer.

It looks like hacking a long-press may cause some problems in some watches: https://forums.garmin.com/developer/connect-iq/f/discussion/7750/detect-long-press-of-back-on-735xt

However, if we come up with a clever way to do this, maybe many other Garmin developers would find it useful. Not sure if it is worth a shot. Will read more about it and report back.
