### ISSUE TITLE
Color blind friendly color scheme

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#35]
> I like the way it is now, but something to keep in mind is color-blind users. Users always ask for colors to denote things, and it's nice to have but there are a lot of people out there who may not be able to distinguish between them. It's always a good idea to have color be additional and the primary method of visually notifying status should be something that doesn't require it. I'm not really sure how to do that here because the font sizes are difficult to work with. Also, I'm not color blind so I don't know how easily someone can distinguish what's there now. Maybe we just sit on any changes until we have a better suggestion. I think it's usable as-is.

**Comment by nilsbenson** [comment]
I was thinking, with a dynamic list we could also tweak the font size of the entry based on how close it is to done. OR if we dynamically ordered based on closeness that would suffice. We could also do both - as the timers tick down, color changes, order of the list changes, and the font sizes adjust a bit to get larger the closer they get to a flip.

**Comment by hhdegen** [comment]
- When you use colors for text, you should check the contract between the font color and the background color ... try it here: https://webaim.org/
- For color blind people, you need a second encoding channel, e.g. symbols, represented through icons, or text.
- You may also consider the font sizes. Here you find a fontsize calculator: https://www.leserlich.info/werkzeuge/schriftgroessenrechner/index-en.php

**Comment by arquicanedo** [comment]
@hhdegen thanks for the pointers. Will check them out. These two pages are useful. We are currently discussing the font size increase as an indicator for a timer expiring soon. But that would be in the works in a mid-term future.

**Comment by nilsbenson** [comment]
one possibility is to keep the current colors, but tweak the font size or boldness of the timer display (start smaller, end larger?) the closer it gets to firing.

Another possibility would be to add a growing flame icon, or change the size of the flip icon based on how close it is.

![image](https://user-images.githubusercontent.com/814623/84714058-30318a00-af32-11ea-9256-b178f38fd883.png)

**Comment by arquicanedo** [comment]
The flame icon is a great idea: "you're steak is on fire."

**Comment by nilsbenson** [comment]
with the flame icon I think we can close this out for now -- we have both contextual (color) and more obvious graphical (flame icon) ways of displaying to the user that they may need to check on things.

**Comment by arquicanedo** [comment]
closing as we have the first version.
