### ISSUE TITLE
How to best use large screens and powerful watches

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#37]
> Following up on my previous comment, for larger screens we can allow for a bit more functionality. Basically "growing into the device". I've had to do a lot of this developing web front ends that support desktop to mobile devices and mobile apps that support a variety of phones with different capabilities. The more the watch offers us, the more we can offer the user. What those things are I don't really know other than more refined layouts right now, but users want to see fancier stuff on their fancier devices. This is also going to require working out a "more complicated" build process so that we can keep memory usage low on low-ram devices and only build in the parts of the code that can actually be used. This would involve at least using monkey barrels and probably something along the lines of the #ifdef support discussed here:
https://forums.garmin.com/developer/connect-iq/f/discussion/7733/solution-for-line-by-line-mc-conditional-compilation/1075703#1075703

**Comment by nilsbenson** [comment]
it would be interesting to see what we can do with the "dead space" on the watches.

For semi-circular like the FR235:

![image](https://user-images.githubusercontent.com/814623/84713870-ada8ca80-af31-11ea-98c7-dc790c941a9c.png)


For circular watches like the fenix:

![image](https://user-images.githubusercontent.com/814623/84713931-d0d37a00-af31-11ea-8ec8-ec87a02e9763.png)

For rectangular devices almost all of them have a ton of room to work with. It would be neat if we could put some more info in these spaces like gps on / activity on / a bar that shows whatever the "total time" count left is, etc.

**Comment by arquicanedo** [comment]
The total time for the selected steak makes sense. I feel adding another timer on the screen would be impossible given the space. The user can bring focus to the steak that needs total time attention and that info is shown. I think this is very clean.

If GPS enabled we can show the GPS strength like in other apps. Activity on/off is good too.

**Comment by arquicanedo** [comment]
We've added a bunch of context to the top/bottom of the screen. Closing for now.
