### ISSUE TITLE
My phone speaks out the laps as things are flipped

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#39]
During my test I had my phone with me. The watch + CIQ app on the phone decided it would be hilarious if they talked and phone spoke the laps out to me as I was flipping. I didn't even know this was a thing and I don't really like it. Need to see if we can disable activity voice prompts for this specific app.

**Comment by arquicanedo** [comment]
haha that's crazy. I'm glad my fr235 does not talk.

**Comment by nilsbenson** [comment]
Looks like the only way to disable this is to stop voice prompts for activities (lap, etc) from the watch settings. Applications have no control over this.

I think the best way to handle this is to probably allow for an app settings menu that allows the user to:

- enable/disable GPS
- enable/disable activity tracking completely

**Comment by arquicanedo** [comment]
We can do that. I can imagine how annoying it would be to have the phone/watch talk to you every 2 minutes.

**Comment by nilsbenson** [comment]
edited the battery drain issue to contain the enable/disable GPS and activity. closing this one as there's not much we can do about it but users CAN disable speaking during activities from the watch settings.
