### ISSUE TITLE
Timer reset weirdness when changing times for an existing timer

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#41]
I haven't been able to figure out the exact steps but this has happened twice:

- Start with a custom timer
- let it run, auto flip, etc
- set to another custom value
- let it run
- try to set to a preset value (1/2/3/4/5)
- it fails to set to the proper time and seems to set to 1 minute

This is the rough set of steps but I've only been able to reproduce it on accident while using the app so I'm not 100% sure what's happening.

**Comment by arquicanedo** [comment]
Interesting. Will try to reproduce it with the steps above today and report back if the same behavior is observed.

**Comment by nilsbenson** [comment]
found a type in the resources and fixed it. I don't recall but it's highly possible that when I see this it was because I was trying to pick 4 minutes. Will continue looking at it.

**Comment by nilsbenson** [comment]
I'm closing this - used it several times yesterday for 20-30 minutes at a time with various timer changes and was unable to reproduce after the fixes we pushed. I'm leaning towards the typo being the problem. It seems I like the 4 minute setting for whatever reason.
