### ISSUE TITLE
Allow users to disable/enable GPS and activity recording

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#42]
It may just be because I've been using the watch a lot for other things, but also may be related to making the app controller static but I've noticed heavy batter drain since installing and using the dev build.

Regardless of whether it's my usage or if it's a bug we should make a quick pass and:

- add a shutdown() method to the controller that stops timers / cleans up event subscriptions / stops GPS / etc
- call this method in the place(s) the app exits to make sure all timers and everything are stopped as the app closes

This should probably be called in the App class when the app is exiting.

**Comment by arquicanedo** [comment]
I took a first pass at the shutdown() method.

These two lines have been there for a while. I don't know where I got this from but I could not find any documentation about the SimpleCallbackEvent.

```
	public var timerChanged = new SimpleCallbackEvent("timerChanged");
	public var flipChanged = new SimpleCallbackEvent("flipChanged");
```

The shutdown method sets them to null.

**Comment by arquicanedo** [comment]
Less vibration probably helps battery optimization so I like your new duration. It feels much more natural than the long one. I also changed the settings to the flipVibrator. In practice, I dont care so much having two types of vibrators to indicate start or a flip.

**Comment by nilsbenson** [comment]
Going to leave this case open until we have a chance to look at the ability to disable activity and GPS tracking. Those are probably the top 2 users of the battery now that we've cleaned up the timer drawing.

**Comment by arquicanedo** [comment]
We need to test in the watches to make sure it works. The #46 is related to this.

**Comment by nilsbenson** [comment]
Looks good overall. I do think we need to make sure that if the user turns off the activity recording, that we stop and discard any activity that was already running. Otherwise, the user has to restart the app to pick up the new setting.

**Comment by nilsbenson** [comment]
tested pretty heavily the last couple days, looks good, closing.
