### ISSUE TITLE
Long delay between press and response (FR235)

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#43]
In the Grill menu, there is a long delay of about 2 seconds between the press and the response of the app (">" to move).

**Comment by arquicanedo** [comment]
I got rid of the custom watch face and I have the feeling it improves marginally. This may be related to how old the fr235 is. The dynamic-entries branch is better than development. Perhaps the custom layout improves the experience when compared to the xml layout.

**Comment by nilsbenson** [comment]
![image](https://user-images.githubusercontent.com/814623/84032018-4badfb00-a95c-11ea-8745-8a8a54e63303.png)

The overhead of fetching all the drawables from the resources every time onUpdate() is called is probably a larger overhead than any of the printLln() calls.

Try refactoring the drawables you're updating to be member variables, and only load them once on onShow() with findDrawableById()

Then, in the updateSteakMenu / onUpdate just reference those members for updating the text on the screen. The drawing path is a "hot path" so it should perform the bare minimum amount of work and anything slow in there will cause a poor user experience.

If you're ok with the delay for this release we can focus on optimizing the dynamic list instead, but I think you'll probably see a decent improvement by doing this. On the fenix 6 I don't see any delay so the issue probably just comes down to a little optimization for older devices.

**Comment by arquicanedo** [comment]
@nilsbenson Wow! day and night difference. I'll push the patch.

**Comment by arquicanedo** [comment]
Fixed as suggested by @nilsbenson. Closing.
