### ISSUE TITLE
Activity is created after the app crashes

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#46]
The activity is recorded when the app crashes. It is not a big of a deal but during testing you end up with several failed activities in your history that you then have to delete manually.

I wonder if the app can have a method that is called before panic.

**Comment by nilsbenson** [comment]
I dug around a bit and this is the "normal" behavior of an Activity. If the app crashes the activity is automatically saved by the system. Looking around, beyond attempting try/catch on a couple of things to prevent exceptions from bubbling (which we should do, but it's not a major concern right now) there's no way to have a master error handler. Basically, if an activity is running and your app crashes it will be saved and you don't have control over that.

**Comment by arquicanedo** [comment]
Closing. Normal behavior of an Activity. Thinking about it, it makes sense to have this activity recorded after a crash. I rather have the data than losing it.
