### ISSUE TITLE
Release development to 1.0.0

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#50]
Are you ok in releasing the current development branch as 1.0.0?

**Comment by nilsbenson** [comment]
I'm good with it. I don't think there are serious issues we haven't looked at.

**Comment by arquicanedo** [comment]
Release notes.

- Support for square and round devices
- Screens optimized for each watch
- 4 independent timers with a selector
- Improved user experience (i.e., control over your timers such as a Stop option and easy reconfiguration of flip times)
