### ISSUE TITLE
Timer Menu default times

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#52]
It may be just me, but 1 minute does not do anything to food. I don't think I have ever used a 1 minute timer. 

Now that we have the Custom Timer, I think we can consider reducing this list to for example:
- Stop
- 2 
- 3
- Custom

**Comment by nilsbenson** [comment]
Do you have any idea what the most common flip times are? I don't think I've ever considered it - 5 is super useful, but even cooking rare is 2? What about for veal? etc. etc.

Agreed generally, maybe the set of time(s) should be based on a quick look at various meats and picking the top 2/3 times and then the custom option.

I was thinking, the stop could be removed and improved by using the menu button on the timer display to perform stop/start. I haven't tested it, but I think the long press on the menu button is sent as a different event than clicking it to go "up". single click for up, long click for stop/start? We could then support 3 default times and a custom without the user having to click around too much to get there.

**Comment by arquicanedo** [comment]
For searing I do 2 per flip. And end up doing about 4 flips total. 

The long press would be neat. The icons would make it explicit.

**Comment by arquicanedo** [comment]
Let's try 2, 3, 5 minutes as defaults. That seems to be the sweet spot at least for the two of us.
