### ISSUE TITLE
can't scroll to change steak selection on vivoactive devices

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#53]
This device has a weird button layout and doesn't appear to support touch. The regular prev/next doesn't work on it because we'll have to support whatever those buttons are manually.

**Comment by arquicanedo** [comment]
In the vivoactive 4 and 3 it works for me. Although no visible buttons, but a click anywhere on the screen seems to be accept. And a scroll up (click+keep pressed for a second and up or down with the mouse) or down and also works. I havent figured out how to "back."

**Comment by nilsbenson** [comment]
The rounds ones and the HR seem to work, but the original rectangular vivoactive is weird. The simulator shows a left and right button but only one seems to do anything. The devices.xml says it's a touch device with swipe support, but we don't get any swipe messages from it.

I was just making a pass at the layouts to see how things looked and found this.. will have to look some more to see what we can do about it.

**Comment by arquicanedo** [comment]
I managed to click up and down in the vivoactive.
![Screen Shot 2020-06-09 at 1 12 06 PM](https://user-images.githubusercontent.com/44371316/84178722-e426a700-aa52-11ea-8bb1-7a1bc6fd081e.png)

**Comment by arquicanedo** [comment]
However, it works on the time selection menu. It does not work in the Grill menu. Perhaps we're using a different event?

**Comment by nilsbenson** [comment]
the buttons are just all weird on this device. You are correct, the scroll works there but doesn't work properly on the steak menu. However, swipes and such DO work properly on the HR and other slightly newer devices. going to look a little more to see if we can handle this cleanly as it seems to be the only device that does this.

**Comment by nilsbenson** [comment]
ok it works it's just a really clumsy interface.

swipe from right to left across the screen sends onNextPage, swipe from left to right across the screen sends onPreviousPage and the selection works as-is.

then, for whatever reason as you found tapping the top and bottom of the screen scrolls the menu. I think this is probably because it was the or one of the first touch devices and they made the firmware fake the regular keypresses instead of using swipe events. 

Closing this, it works as well as any other app on this device would.

![image](https://user-images.githubusercontent.com/814623/84190832-27861300-aa5d-11ea-82e6-ffebf5c3ddb4.png)
