### ISSUE TITLE
After selecting custom timer the screen freezes in the Timer menu

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#55]
Most of the time, when selecting a Custom timer. After clicking accept, the app freezes in the timer menu showing "Custom". 

- If the accept is pressed again (twice), it goes to seconds selection. 
- If press "up" it correctly selects "1" and switches the screen. 
- If press "Down" it correctly selects "59" and switches the screen.
- If press "back" it switches momentarily to the minute selection but goes back to the timer selection.

**Comment by nilsbenson** [comment]
I'm unable to reproduce this in the simulator (fenix 6/fr235) or on my watch (fenix 6).

**Comment by nilsbenson** [comment]
the default selection is strange - it should start at the minutes not the seconds.. 
I pushed a tweak to the duration picker and its delegate to try to simplify it. There was some code in there to try to pick default values that wasn't really needed so I commented it out for now. Maybe this helps.

**Comment by arquicanedo** [comment]
Closing, we'll see if the problem persists.
