### ISSUE TITLE
Can Pickers be initialized to a specific item?

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#57]
Chances are that if you're coking a food type you're doing more than one. Is there a way to initialize a picker to the last selected picker?

**Comment by nilsbenson** [comment]
looks like the Picker base class has a setOptions() method. One of the parameters of that dictionary is "defaults" which is an array containing the index to be selected. 

![image](https://user-images.githubusercontent.com/814623/84713678-33784600-af31-11ea-9d79-b7abe6efb66f.png)

So you would probably just need to look up the index in the BitmapFactory that matches the enum/image type you want, and pass that in to the setOptions method of the picker before showing it.

**Comment by nilsbenson** [comment]
and actually, this could be passed as options to the constructor too (initialize) so when the picker is created we can just tell it which image to select.

**Comment by arquicanedo** [comment]
This worked out great. Now we have the last selected food type. Closing this one and opening a new one to replace the TimeSelectionMenu to be a picker instead of a menu.
