### ISSUE TITLE
TimerSelectionMenu can be a picker

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#59]
- To get the same look and feel as the rest of the pickers
- To pre-select the last time from the list without adding the "(last)" that is more of a hack

**Comment by arquicanedo** [comment]
On second thoughts, the current menu is not bad. Perhaps we delay this until we decide what to do with the total time since the two will be related.

**Comment by nilsbenson** [comment]
Agreed - I think that we may have to introduce a menu between selecting the meat and selecting the time that allows the user to customize the timer type (total time, or regular flip time), the icon for the meat, and the timeout. I'd like to keep the number of clicks required to start a timer to a minimum but I'm having trouble thinking of a better way to do it that's both "obvious" to the user and unobtrusive.

**Comment by arquicanedo** [comment]
Closed for now.
