### ISSUE TITLE
Add icons for activity / GPS status on the steaklist view

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#63]
We can use the dead space to show icons for GPS and activity tracking so the user knows if it's on or off.

**Comment by arquicanedo** [comment]
Added icons but they are not drawing. I thought it was sufficient to loadResource and then dc.drawBitmap but that is not the case. Added some code to SteakMenuView.mc.

**Comment by arquicanedo** [comment]
As an alternative to the slippers we could use a ball to indicate the "activity" (https://www.flaticon.com/free-icon/beach-ball_2918660?term=ball&page=1&position=93)

The arrow for GPS makes sense to me. But I don't mind changing it to a satellite. I think the arrow is clean and what most apps use for location.

**Comment by nilsbenson** [comment]
move the drawing code to onUpdate(). I'm not sure onLayout ever paints the dc it gives you. it's probably there to be able to figure out things like color palette and screen dimensions.

**Comment by arquicanedo** [comment]
Ok, I moved the code to onUpdate(). The problem was that I was drawing **before** View.onUpdate(dc); and this was causing trouble. I'll push a fix shortly.

**Comment by arquicanedo** [comment]
Round and square devices adjusted. However, I'm not the best GUI judge. If you feel there is a better location feel free to adjust.

**Comment by nilsbenson** [comment]
looks good! we'll probably need to make one final pass on layouts/devices before we're ready to release but the couple I checked looked fine. We can probably close this issue out.

**Comment by arquicanedo** [comment]
In testing mode before release.
