### ISSUE TITLE
Add a flame icon to denote how close something is to a flip/done

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#65]
This is in reference to #35 - to reduce the reliance on color we can also display a flame that appears, grows, or both as the timer gets closer to firing.

**Comment by arquicanedo** [comment]
I added the flame when timer gets <= 20 seconds. I think it is a nice feature.

**Comment by nilsbenson** [comment]
looks great! We can probably close this issue

**Comment by arquicanedo** [comment]
Closed for now.
