### ISSUE TITLE
crash when selecting "last time" on edge explore simulator

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#69]
DataStore fetching lastSteakTimeout
************************ comparing 120 [120, 180, 300] = 0
timerCallback
DataStore fetching lastSteakTimeout
Deciding Selection on steak 0 for null seconds

Error: Debugger killed
Stack: 
  - decideSelection() at C:
cs\garmin\barbecueboss-master\source\Controller.mc:331 0x1000184b 
  - onSelect() at C:
cs\garmin\barbecueboss-master\source\TimeSelectionMenuDelegate.mc:57 0x100022fc 
  - onMenuItem() at C:
cs\garmin\barbecueboss-master\source\TimeSelectionMenuDelegate.mc:17 0x100021af

**Comment by arquicanedo** [comment]
I was not able to reproduce. Tried with two "last time" of 0:22 and 2:00 and did ok. 

For some reason the variable did not have the last time set
> Deciding Selection on steak 0 for null seconds

I wonder if it was not saved properly from the datastore.

**Comment by arquicanedo** [comment]
I just looked at where it failed.

>	function decideSelection() {
		var i = self.getSelectedSteak();
		var timeout = self.steaks[i].getTimeout();
		System.println("Deciding Selection on steak " + i + " for " + timeout + " seconds");


The cause probably was the steaks[i].getTimeout() returned null.

**Comment by nilsbenson** [comment]
@arquicanedo I'm going to try to debug this today and see if there is actually an issue here. Works fine on-device for me so I'm not sure if it's actually a problem, or if it's just the simulator.

**Comment by nilsbenson** [comment]
the issue is that we weren't ever saving the last timeout. if a last time wasn't found, we correctly default it to something but when the user selected a timeout for an item we didn't persist that value anywhere.

Tweaked it a little to make sure we save the last user selected timeout, and if we don't find a saved value in the DataStore we don't show the (last) menu item just the default entries.

**Comment by nilsbenson** [comment]
looks good on simulator and device, closing.
