### ISSUE TITLE
FoodType selection icons cropped on round-390x390

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#70]
Venu for example.

![image](https://user-images.githubusercontent.com/44371316/85215741-ca3a6d80-b34a-11ea-8801-6856d20cfe83.png)

**Comment by nilsbenson** [comment]
@arquicanedo I tweaked the size down to make it fit but I'm not sure it's not an issue with the simulator. The LARGE icons seem to fit though in the sim, so we'll just have to see if someone complains about it once released.

**Comment by arquicanedo** [comment]
Sounds good. Closing for now and wait for any complaints.
