### ISSUE TITLE
User feedback v.1.1.0

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#77]
> Hello

> Thank you. I agree that you're taking giant leaps in the right direction.
I like the icons, they can be used for distinguishing between different steaks as well (mine, kids', wife's). You have gone with a UI mimicking a particular series (Forerunner)? To me the icons for functions and the on/off switch in settings are strange to look at since it does not match the UI on the Fenix series - but this is no biggie.

I'll take a look at the Fenix button layout but in the simulator it looks like a similar layout of buttons to that of the forerunners. 

> So my prioritized wish list is now:

> Total time per steak, as well as time to next flip

Will be addressed in future version. We have an open issue for this.

> Ability to save last flip time per "position", so that if the first steak last time had 1:10 per flip, and the second it the list had 1:30, the first will still show "1:10 (last time)" and the second "1:30 (last time) - since it's somewhat a pain to set a large number of different flip times each session (and they're always more or less the same for me)

This is a variant of what we have now. We need to track a "lastTimer" per steak in the steakList. Although I am not convincedt that this makes the experience any better than now.

> And small stuff on top would make it better (maybe just for me)
Only show the amount of steaks active - (makes for easier overview), maybe with slightly larger font - are you using a custom font?
Make the UI in line with Fenix

Same as above. Will look into the Fenix button layout.

**Comment by nilsbenson** [comment]
I think maybe he's referring to the icons, toggles, etc. We could update those to use Menu2 on newer devices where it's available.

I do like both of the other suggestions though - dynamic number of entries until the screen is full so we don't have to write any page scrolling for the list, and saving all the usage settings on exit and reloading on start. I think a lot of people probably end up with a couple of timers that they use for specific things (I know I do this) and it would be convenient for the app to save those settings.

**Comment by arquicanedo** [comment]
Yes, he refers to the icons. 

> What I mean is the standard way of showing enabled/diabled options on a Fenix6 is like this:
> https://hikingguy.com/wp-content/uploads/fenix-6-battery-saver-1536x864.jpg
> This what I meant with non-standard UI. I just sort of expected that in the Dev kit there is some standard function that draws UI for different watches differently, but maybe I am mistaken?

Is there an easy way to support the Menu2? I remember we discussed this at some point but it sounded like we had to have a complex build environment.

Ok, I see what you mean with the frequently used timers. It makes sense. I do the same. There are some things I cooked regularly that are always the same. 

We could hide the inactive timers, and replace the text with "New timer" always at the bottom. That way we grow until we run out of space.

**Comment by nilsbenson** [comment]
Menu2 can be supported by testing for it with "has", so that one's not bad. Also, I've done a lot of research on the build stuff and it's not really that bad to get it working. However, unless there's a problem with memory usage we can implement that particular bit without dealing with the jungle file.

For integrating the bluetooth thermometer support we will have to use the jungle file, there's no way to avoid it. No point in building a bunch of extra code for devices that don't have the hardware or the CIQ version to support it.

**Comment by arquicanedo** [comment]
I would put the Menu2 as a low priority. I rather spend my time on the smoking functionality than in supporting Menu2. 

I had a quick look at the jungle file description in the developer's page. If I understood correctly, jungle files are reusable/ libraries. This makes sense and make it cleaner. 

My dongle was shipped today. Hopefully arrives this week.

**Comment by nilsbenson** [comment]
I don't really mind looking at the menu thing. If you want to start looking at saving the item settings on exit and think a bit about how we fit the total time into the app, I can fix the outstanding bugs in development and see if how much time/if it's worth adding Menu2 support for CIQ 3.x devices.

When I'm done with that I'm going to take the bluetooth code I wrote and turn it into a monkey barrel (that's the reusable library) and add it to the project in low-n-slow. We will need to update the jungle file then (that's the "build script"). By then you should have your dongle and we'll be ready to start making some headway on the temperature and smoking stuff.

MonkeyBarrel (barrel): reusable library, like stuff you get from pip for python or .so in unix, .dll in windows, etc. except used as a code library, not a pre-built binary

Jungle file: kind of equivalent to a makefile, ant or gradle script. controls what files/resources/annotations get compile on a per-device/family/language level

**Comment by arquicanedo** [comment]
Ok. I like the plan. 
- I'll bring the total time discussion to its issue.
- I'll implement the saving of item settings per steak on exit.
- I'll fix the activity saving bug when no timer has been initiated.

**Comment by arquicanedo** [comment]
Closing, well identified improvements and new functions. Tracking in independent tickets.
