### ISSUE TITLE
Settings - Activity Recording in FR235 overlaps with button

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#78]
Not a big deal but looks odd. Need to check all other configurations.

![Screen Shot 2020-06-29 at 5 37 28 PM](https://user-images.githubusercontent.com/44371316/86058953-c6d07180-ba2f-11ea-9357-3f9b767454f7.png)

**Comment by nilsbenson** [comment]
I thought I had fixed this when I made a pass on the settings view. I guess I missed it. There are some params available in the layout that can control the font size and positioning to clean it up. The toggle icons are always justified all the way to the right so you don't need to adjust them.

**Comment by arquicanedo** [comment]
Fixed for the next release.
