### ISSUE TITLE
Implement Menu2 support for the settings menu where available

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#81]
To integrate a little more cleanly with newer devices we should use Menu2 / ToggleMenuItem / etc for the settings menu.

**Comment by arquicanedo** [comment]
It does look great!

I just looked at the fr235 and the Garmin apps use a primitive version of this. I'll investigate whether this is accessible via de CIQ 1.4. This would be the best option for old devices.

![image](https://user-images.githubusercontent.com/44371316/86186843-226e2e00-bb08-11ea-80b8-2c6f2e4a3305.png)

**Comment by nilsbenson** [comment]
It's not worth the effort. We only have access to the original Menu like what's being used for the timeout selection on 1.4. We could modify the ListDrawable in the future to look more like this, but it's a lot of work for little reward. Updating the menus for the newer devices only took about an hour and is a big improvement.

**Comment by arquicanedo** [comment]
This is done for settings and for barbecue settings. Closing.
