### ISSUE TITLE
[low-n-slow-totaltime] Out of memory

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#87]
@nilsbenson is the Out of Memory related to the lines of code, the dynamic memory allocation, or both? The low-n-slow-totaltime runs out of memory in several instances. This comes randomly. 

What can I do to reduce the memory footprint?

**Comment by arquicanedo** [comment]
I just saw your comment on WelcomeView related to the logoImage. I'll create the smaller size logos.

Error: Out Of Memory Error
Details: Failed invoking <symbol>
Stack: 
  - onShow() at /Users/canedo/eclipse-workspace/barbecue_app/source/WelcomeView.mc:33 0x10000657

**Comment by nilsbenson** [comment]
added #90 as one of the steps to take to reduce memory use

**Comment by nilsbenson** [comment]
going to close this for now. We have some extra space free now for the 64kb devices and it should be enough if we're careful.
