### ISSUE TITLE
Long press 

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#88]
Here a [thread](https://forums.garmin.com/developer/connect-iq/f/discussion/2155/handling-long-button-press) discussing the long press. This would be good to simplify the menus. The longpress > 2 second can mean stop whereas <= 1 second can mean flip.

Although not critical, could be an enhancement.

**Comment by arquicanedo** [comment]
From the thread above and [this one](https://forums.garmin.com/developer/connect-iq/f/discussion/7750/detect-long-press-of-back-on-735xt) it is clear that this is a hack and long presses cannot be universally detected in all watches.

**Comment by nilsbenson** [comment]
Do we get a long press on the lap/back button?

We don't use it for much, and on watch devices I think it makes sense to use the lap functionality as a kind of flip or reset.

**Comment by arquicanedo** [comment]
There is some recent (a day old) activity in the [forums](https://forums.garmin.com/developer/connect-iq/f/discussion/2155/handling-long-button-press/26935#26935). However, I don't see anything in the [documentation](https://developer.garmin.com/connect-iq/api-docs/Toybox/WatchUi/InputDelegate.html). It looks like it is still a hack.

**Comment by arquicanedo** [comment]
Closing for now. We will revive if we get to the point where this is essential. But I don't think that would be the case. All the functionality is mapped nicely to the available buttons.
