### ISSUE TITLE
[Tenergy/Simulator] Device Scan Crash

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#95]
On fr945 when Device Scanning generated this trace and crash

Starting BTLE scan
connected changed
connected
onConnectedStateChanged (device param) device: null
onConnectedStateChanged (service.getDevice()) device: null
onConnectedStateChanged (char.getService().getDevice().getName()) device: null
char write: 0
enabling notifications for characteristic on device iBBQ
desc write 00002902-0000-1000-8000-00805F9B34FB: 0
Stopping BTLE scan

Error: Unexpected Type Error
Details: Failed invoking <symbol>
Stack: 
  - onConnectionChanged() at /Users/canedo/eclipse-workspace/barbecue_app/source/Views/Smoke/SmokeView.mc:80 0x100024e3 
Scan state changed: 0 - 0
event: timerChanged already has a callback when subscribing

**Comment by arquicanedo** [comment]
I cleaned the App Data in the simulator and this got rid of the crash I was getting above. Still, will check later.

**Comment by nilsbenson** [comment]
I made a pass to make sure that all settings get initialized to a known value on app start to ensure we don't see things like this.

**Comment by arquicanedo** [comment]
Closing.
