### ISSUE TITLE
[Tenergy] Custom timer should allow hh:mm:ss format

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#96]
Smoking sessions need hours.

**Comment by nilsbenson** [comment]
agreed. we need to modify the duration picker to allow for hours, and configurable so we can disable that on the flip/total timers.

I think we drop the seconds on the display in SmokeView - it's not terribly useful and you can see the lag when it updates and it's also getting temperature data from the probe at the same time.

**Comment by arquicanedo** [comment]
I pushed a change to allow for MM:SS and HH:MM. The only difference is the text at the top. The caller should interpret the meaning of the time array (time[0]*60 + time[2]). 

Since the smokerView is updating every minute, would it make sense to create another timer? I think old devices support up to 3 timers. I read that somewhere in the forums.

**Comment by nilsbenson** [comment]
looks good, works well for the smoke-related times

**Comment by arquicanedo** [comment]
Closing
