### ISSUE TITLE
[Menu2] How to dynamically update a MenuItem

### ISSUE THREAD

**Issue by arquicanedo** [arquicanedo/barbecueboss#97]
In 81acb49 I added a DurationPicker for waterCheck. However, after selecting the value and updating the item's subLabel it does not update the value. It works after going out of the screen and starting it again. 

Do you know what the trick is do dynamically update the content?

I tried explicitly with menu2.updateItem(item, index) but does not seem to work either.
I also tried watchUi.requestUpdate() but didn't work.

**Comment by nilsbenson** [comment]
see what I did in 9894fc4

- you have to introduce some kind of method outside the handling of the specific menu item to update the contents. I added an event that gets fired when ANY of the smoke settings change (water/temp/smoke) and the menu items get updated.

**Comment by arquicanedo** [comment]
This is great. I saw how it is done. Thanks.

Closing.
