### ISSUE TITLE
implement jungle file annotation excludes for all devices

### ISSUE THREAD

**Issue by nilsbenson** [arquicanedo/barbecueboss#99]
there are three annotations that need to be conditionally excluded based on the device:

:btle - should be excluded on any device that is not at least CIQ3 or does not have BTLE support
:smoke - should be excluded from any device that won't support the smoking functionality
:ciq3 - should be excluded on any device that is not at least CIQ3 (primarily used to drive Menu vs. Menu2)
:ciq1 - possibly needs to be excluded from any device newer than CIQ1 but I used it a little liberally so this one needs some investigation

two devices are implemented - vivoactive and fr235 to exlude stuff they can't support. We need to look at all supported devices and add the exclusions to the monkey.jungle file in the bbq boss project.

**Comment by arquicanedo** [comment]
This is working great and it does have a big impact in memory utilization. This saved the low memory CIQ1 devices. Closing.
